# 03_sex_hormone_programs_figure1b.R
# Wells et al. 2020 Figure 1b reanalysis: sex hormone receptor/program analysis
#
# 目的：
#   1. 接上 02_run_pca_umap.R 生成的 output/control_seurat_pca_umap.rds
#   2. 在 Figure 1b 的 mTEC/cTEC states 中查看性激素受体分布
#   3. 计算 estrogen / androgen / progesterone response gene-set scores
#   4. 查看这些 score 与 Aire-associated / antigen presentation / tuft-like programs 的关系
#
# 重要定位：
#   - 这个 Figure 1b atlas 来自 female WT mice；本脚本不做雌雄差异比较。
#   - 本脚本只分析 sex hormone axis：androgen / estrogen / progesterone。
#   - 为保护主课题，本脚本刻意不分析 glucocorticoid receptor 或 GC response genes。
#
# 输入：
#   output/control_seurat_pca_umap.rds
#
# 输出：
#   output/03_sex_hormone_figure1b/
#
# 建议运行顺序：
#   source("scripts/03_sex_hormone_programs_figure1b.R")

rm(list = ls())
gc()

# -------------------------------------------------------------------------
# 0. 自动寻找 项目根目录
# -------------------------------------------------------------------------

required_relative_file <- file.path("output", "control_seurat_pca_umap.rds")

get_project_root <- function() {
  current <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
  for (i in 1:5) {
    if (dir.exists(file.path(current, "data")) &&
        dir.exists(file.path(current, "scripts"))) {
      return(current)
    }
    parent <- dirname(current)
    if (parent == current) break
    current <- parent
  }
  stop("Could not find project root containing both data/ and scripts/")
}

project_root <- get_project_root()

if (!file.exists(file.path(project_root, required_relative_file))) {
  stop(
    "Expected file:\n",
    required_relative_file,
    "\n\nCurrent working directory:\n",
    getwd(),
    "\n\nPlease run 01_create_seurat_object.R and 02_run_pca_umap.R first."
  )
}

output_dir   <- file.path(project_root, "output")
input_file   <- file.path(output_dir, "control_seurat_pca_umap.rds")
result_dir   <- file.path(output_dir, "03_sex_hormone_figure1b")
result_file  <- file.path(output_dir, "control_seurat_sex_hormone_figure1b.rds")

dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)

cat("Project root:\n", project_root, "\n\n", sep = "")
cat("Input file:\n", input_file, "\n\n", sep = "")
cat("Output directory:\n", result_dir, "\n\n", sep = "")

# -------------------------------------------------------------------------
# 1. 检查 packages
# -------------------------------------------------------------------------

required_packages <- c("Seurat", "SeuratObject", "ggplot2", "Matrix")

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Missing R package(s): ",
    paste(missing_packages, collapse = ", "),
    "\n\nInstall them first with:\n",
    'install.packages(c("Seurat", "SeuratObject", "ggplot2", "Matrix"))'
  )
}

cat("Package versions:\n")
for (pkg in required_packages) {
  cat("  ", pkg, ": ", as.character(utils::packageVersion(pkg)), "\n", sep = "")
}
cat("\n")

# msigdbr 是可选包；有它时自动读取 GO gene sets，没有时使用小型 fallback gene sets。
use_msigdbr <- requireNamespace("msigdbr", quietly = TRUE)
if (!use_msigdbr) {
  warning(
    "Package 'msigdbr' is not installed. ",
    "The script will use small fallback gene sets. ",
    "For publication-quality gene-set scoring, install it with: install.packages('msigdbr')"
  )
}

# -------------------------------------------------------------------------
# 2. 读取对象，并确认需要的 metadata / reduction
# -------------------------------------------------------------------------

cat("===== 1. Loading processed Seurat object =====\n")

control_obj <- readRDS(input_file)
SeuratObject::DefaultAssay(control_obj) <- "RNA"

cat("\nInput object:\n")
print(control_obj)

required_meta <- c("stage_figure1b", "stage_plot", "exp")
missing_meta <- setdiff(required_meta, colnames(control_obj[[]]))

if (length(missing_meta) > 0) {
  stop(
    "Required metadata column(s) missing: ",
    paste(missing_meta, collapse = ", "),
    "\nPlease make sure this object was generated by 02_run_pca_umap.R."
  )
}

reduction_name <- if ("umap_reanalysis" %in% SeuratObject::Reductions(control_obj)) {
  "umap_reanalysis"
} else if ("umap" %in% SeuratObject::Reductions(control_obj)) {
  "umap"
} else {
  stop("No UMAP reduction found. Expected 'umap_reanalysis' from 02_run_pca_umap.R.")
}

cat("\nUMAP reduction used for plotting: ", reduction_name, "\n", sep = "")

# Figure 1b-style analysis excludes unknown cells, matching your plotting strategy.
figure1b_obj <- subset(
  control_obj,
  subset = stage_figure1b != "unknown"
)

figure1b_obj$stage_plot <- droplevels(figure1b_obj$stage_plot)

cat("\nCells retained for Figure 1b-style analysis:\n")
print(sort(table(figure1b_obj$stage_plot), decreasing = TRUE))

# -------------------------------------------------------------------------
# 3. 通用函数
# -------------------------------------------------------------------------

get_data_layer <- function(obj, assay = "RNA") {
  mat <- tryCatch(
    {
      SeuratObject::LayerData(obj[[assay]], layer = "data")
    },
    error = function(e) NULL
  )

  if (is.null(mat)) {
    mat <- Seurat::GetAssayData(obj, assay = assay, slot = "data")
  }

  mat
}

scale_vector <- function(x) {
  z <- as.numeric(scale(x))
  z[!is.finite(z)] <- 0
  z
}

calculate_mean_expression_score <- function(obj, data_mat, genes, score_name, min_genes = 3) {
  present_genes <- intersect(genes, rownames(data_mat))

  if (length(present_genes) < min_genes) {
    warning(
      "Gene set '", score_name, "' has only ", length(present_genes),
      " genes present in the dataset. Score will be set to NA."
    )
    obj[[score_name]] <- NA_real_
    return(list(obj = obj, present_genes = present_genes, raw_score = rep(NA_real_, ncol(obj))))
  }

  raw_score <- Matrix::colMeans(data_mat[present_genes, colnames(obj), drop = FALSE])
  obj[[score_name]] <- scale_vector(raw_score)

  list(obj = obj, present_genes = present_genes, raw_score = raw_score)
}

save_plot <- function(plot, filename, width = 7, height = 5, dpi = 300) {
  ggplot2::ggsave(
    filename = file.path(result_dir, paste0(filename, ".png")),
    plot = plot,
    width = width,
    height = height,
    dpi = dpi
  )

  ggplot2::ggsave(
    filename = file.path(result_dir, paste0(filename, ".pdf")),
    plot = plot,
    width = width,
    height = height
  )
}

# -------------------------------------------------------------------------
# 4. 性激素受体表达：Ar / Esr1 / Esr2 / Gper1 / Pgr
# -------------------------------------------------------------------------

cat("\n===== 2. Sex hormone receptor expression =====\n")

data_mat <- get_data_layer(control_obj, assay = "RNA")

sex_receptors <- c("Ar", "Esr1", "Esr2", "Gper1", "Pgr")
present_receptors <- intersect(sex_receptors, rownames(control_obj))
missing_receptors <- setdiff(sex_receptors, rownames(control_obj))

cat("Sex hormone receptor genes requested:\n")
print(sex_receptors)
cat("\nPresent receptor genes:\n")
print(present_receptors)
cat("\nMissing receptor genes:\n")
print(missing_receptors)

if (length(present_receptors) == 0) {
  stop("None of the sex hormone receptor genes were found in this object.")
}

utils::write.csv(
  data.frame(
    gene = sex_receptors,
    present_in_object = sex_receptors %in% rownames(control_obj)
  ),
  file = file.path(result_dir, "03A_sex_receptor_presence.csv"),
  row.names = FALSE,
  quote = FALSE
)

# DotPlot：比单独 FeaturePlot 更适合低表达 receptor genes。
dot_receptors <- Seurat::DotPlot(
  object = figure1b_obj,
  features = present_receptors,
  group.by = "stage_plot",
  assay = "RNA"
) +
  ggplot2::labs(
    title = "Sex hormone receptor expression across Figure 1b states",
    x = NULL,
    y = NULL,
    color = "Average\nexpression",
    size = "% cells\nexpressing"
  ) +
  ggplot2::theme_classic() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
    plot.title = ggplot2::element_text(hjust = 0.5)
  )

save_plot(dot_receptors, "03A_dotplot_sex_receptors_by_stage", width = 7.2, height = 4.8)

# FeaturePlot：每个 receptor 单独保存，便于检查 dropout / spatial pattern。
for (gene in present_receptors) {
  p_gene <- Seurat::FeaturePlot(
    object = figure1b_obj,
    features = gene,
    reduction = reduction_name,
    pt.size = 0.75,
    order = TRUE,
    raster = FALSE
  ) +
    ggplot2::labs(title = paste0(gene, " expression")) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.text = ggplot2::element_blank(),
      axis.ticks = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(hjust = 0.5)
    )

  save_plot(p_gene, paste0("03B_featureplot_", gene), width = 5.2, height = 4.8)
}

# receptor expression summary by state: average expression and percent expressed.
expr_receptor <- data_mat[present_receptors, colnames(figure1b_obj), drop = FALSE]
stage_vector <- as.character(figure1b_obj$stage_plot)
stage_levels <- levels(figure1b_obj$stage_plot)

avg_receptor_by_stage <- sapply(
  stage_levels,
  function(st) {
    cells <- colnames(figure1b_obj)[stage_vector == st]
    Matrix::rowMeans(expr_receptor[, cells, drop = FALSE])
  }
)

pct_receptor_by_stage <- sapply(
  stage_levels,
  function(st) {
    cells <- colnames(figure1b_obj)[stage_vector == st]
    Matrix::rowMeans(expr_receptor[, cells, drop = FALSE] > 0) * 100
  }
)

utils::write.csv(
  avg_receptor_by_stage,
  file = file.path(result_dir, "03A_average_receptor_expression_by_stage.csv"),
  quote = FALSE
)

utils::write.csv(
  pct_receptor_by_stage,
  file = file.path(result_dir, "03A_percent_receptor_positive_by_stage.csv"),
  quote = FALSE
)

# -------------------------------------------------------------------------
# 5. 从 MSigDB/GO 或 fallback gene sets 构建 sex hormone response gene sets
# -------------------------------------------------------------------------

cat("\n===== 3. Building sex hormone response gene sets =====\n")

msig_terms_used <- list()

get_msig_go_bp <- function() {
  if (!requireNamespace("msigdbr", quietly = TRUE)) {
    return(NULL)
  }

  msig_fun <- msigdbr::msigdbr
  msig_args <- names(formals(msig_fun))

  msig <- tryCatch(
    {
      if ("collection" %in% msig_args) {
        msigdbr::msigdbr(
          species = "Mus musculus",
          collection = "C5",
          subcollection = "GO:BP"
        )
      } else {
        msigdbr::msigdbr(
          species = "Mus musculus",
          category = "C5",
          subcategory = "GO:BP"
        )
      }
    },
    error = function(e) {
      warning("Could not load msigdbr GO:BP gene sets: ", conditionMessage(e))
      NULL
    }
  )

  msig
}

build_msig_gene_set <- function(msig, pattern, label) {
  if (is.null(msig)) {
    return(character(0))
  }

  if (!all(c("gs_name", "gene_symbol") %in% colnames(msig))) {
    warning("msigdbr output does not contain expected columns: gs_name and gene_symbol.")
    return(character(0))
  }

  selected_terms <- unique(msig$gs_name[grepl(pattern, msig$gs_name, ignore.case = TRUE)])
  selected_genes <- sort(unique(msig$gene_symbol[msig$gs_name %in% selected_terms]))

  msig_terms_used[[label]] <<- selected_terms
  selected_genes
}

msig_go_bp <- get_msig_go_bp()

if (!is.null(msig_go_bp)) {
  cat("msigdbr GO:BP terms loaded: ", length(unique(msig_go_bp$gs_name)), "\n", sep = "")
}

# 只抓 sex hormone 相关 terms，不抓 broad hormone 或 steroid terms。
sex_hormone_gene_sets <- list(
  Estrogen_response = build_msig_gene_set(
    msig_go_bp,
    pattern = "ESTROGEN|ESTRADIOL",
    label = "Estrogen_response"
  ),
  Androgen_response = build_msig_gene_set(
    msig_go_bp,
    pattern = "ANDROGEN",
    label = "Androgen_response"
  ),
  Progesterone_response = build_msig_gene_set(
    msig_go_bp,
    pattern = "PROGESTERONE",
    label = "Progesterone_response"
  )
)

# fallback gene sets：仅用于 msigdbr 不可用或返回空集时的初步测试。
fallback_gene_sets <- list(
  Estrogen_response = c(
    "Esr1", "Esr2", "Gper1", "Pgr", "Greb1", "Tff1", "Cebpb",
    "Fos", "Jun", "Stat3", "Socs3", "Ccnd1", "Bcl2", "Myc"
  ),
  Androgen_response = c(
    "Ar", "Ncoa1", "Ncoa2", "Ncoa3", "Fkbp4", "Fkbp5",
    "Foxa1", "Cebpb", "Fos", "Jun", "Myc"
  ),
  Progesterone_response = c(
    "Pgr", "Pgrmc1", "Pgrmc2", "Ncoa1", "Ncoa2", "Ncoa3",
    "Fkbp4", "Fkbp5", "Cebpb", "Fos", "Jun"
  )
)

for (nm in names(sex_hormone_gene_sets)) {
  if (length(sex_hormone_gene_sets[[nm]]) == 0) {
    warning("Using fallback gene set for ", nm, ".")
    sex_hormone_gene_sets[[nm]] <- fallback_gene_sets[[nm]]
    msig_terms_used[[nm]] <- "fallback_gene_set_used"
  }
}

# 保存 MSigDB/GO terms 信息。
for (nm in names(msig_terms_used)) {
  utils::write.table(
    msig_terms_used[[nm]],
    file = file.path(result_dir, paste0("03C_terms_used_", nm, ".txt")),
    quote = FALSE,
    row.names = FALSE,
    col.names = FALSE
  )
}

# -------------------------------------------------------------------------
# 6. 计算 sex hormone response scores + mTEC biology scores
# -------------------------------------------------------------------------

cat("\n===== 4. Calculating module scores =====\n")

# 这些 biological programs 用来解释 sex hormone scores 是否偏向 Aire/mimetic/tolerance-related states。
# 注意：这里不加入任何 GC-related genes。
additional_gene_sets <- list(
  Aire_Fezf2_core = c("Aire", "Fezf2"),
  Antigen_presentation = c(
    "Cd74", "H2-Aa", "H2-Ab1", "H2-Eb1", "H2-DMa", "H2-DMb1",
    "B2m", "Tap1", "Tap2", "Psmb8", "Psmb9"
  ),
  Tuft_program = c("Pou2f3", "Trpm5", "Dclk1", "Avil", "Gnat3", "Il25", "Alox5ap"),
  Ccl21a_high_program = c("Ccl21a", "Ccl19", "Krt5", "Krt14", "Ltbr", "Relb"),
  cTEC_program = c("Ackr4", "Prss16", "Psmb11", "Ctsl", "Pax1", "Cxcl12")
)

all_gene_sets <- c(sex_hormone_gene_sets, additional_gene_sets)
score_columns <- character(0)
gene_set_summary <- data.frame()

for (set_name in names(all_gene_sets)) {
  score_name <- paste0(set_name, "_z")

  score_result <- calculate_mean_expression_score(
    obj = control_obj,
    data_mat = data_mat,
    genes = all_gene_sets[[set_name]],
    score_name = score_name,
    min_genes = ifelse(set_name == "Aire_Fezf2_core", 1, 3)
  )

  control_obj <- score_result$obj
  score_columns <- c(score_columns, score_name)

  gene_set_summary <- rbind(
    gene_set_summary,
    data.frame(
      gene_set = set_name,
      score_column = score_name,
      input_genes = length(unique(all_gene_sets[[set_name]])),
      present_genes = length(score_result$present_genes),
      present_gene_symbols = paste(score_result$present_genes, collapse = ";"),
      stringsAsFactors = FALSE
    )
  )
}

utils::write.csv(
  gene_set_summary,
  file = file.path(result_dir, "03C_gene_set_summary.csv"),
  row.names = FALSE,
  quote = FALSE
)

# 重新生成 figure1b_obj，使其包含刚刚新增的 module scores。
figure1b_obj <- subset(
  control_obj,
  subset = stage_figure1b != "unknown"
)
figure1b_obj$stage_plot <- droplevels(figure1b_obj$stage_plot)

sex_score_columns <- c(
  "Estrogen_response_z",
  "Androgen_response_z",
  "Progesterone_response_z"
)
sex_score_columns <- intersect(sex_score_columns, colnames(figure1b_obj[[]]))

# -------------------------------------------------------------------------
# 7. sex hormone response scores：UMAP + violin/boxplot
# -------------------------------------------------------------------------

cat("\n===== 5. Plotting sex hormone response scores =====\n")

for (score_col in sex_score_columns) {
  p_score <- Seurat::FeaturePlot(
    object = figure1b_obj,
    features = score_col,
    reduction = reduction_name,
    pt.size = 0.75,
    order = TRUE,
    raster = FALSE
  ) +
    ggplot2::labs(title = gsub("_z$", " score", score_col)) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.text = ggplot2::element_blank(),
      axis.ticks = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(hjust = 0.5)
    )

  save_plot(p_score, paste0("03C_featureplot_", score_col), width = 5.2, height = 4.8)
}

# Violin plot long data frame
score_meta <- figure1b_obj[[]]
score_long <- do.call(
  rbind,
  lapply(
    sex_score_columns,
    function(score_col) {
      data.frame(
        cell = rownames(score_meta),
        stage_plot = score_meta$stage_plot,
        exp = score_meta$exp,
        score_name = score_col,
        score = score_meta[[score_col]],
        stringsAsFactors = FALSE
      )
    }
  )
)

score_long$score_name <- factor(
  score_long$score_name,
  levels = sex_score_columns,
  labels = gsub("_z$", "", sex_score_columns)
)

p_violin <- ggplot2::ggplot(
  score_long,
  ggplot2::aes(x = stage_plot, y = score)
) +
  ggplot2::geom_violin(trim = TRUE, scale = "width", linewidth = 0.25) +
  ggplot2::geom_boxplot(width = 0.12, outlier.size = 0.2, linewidth = 0.25) +
  ggplot2::facet_wrap(~ score_name, ncol = 1, scales = "free_y") +
  ggplot2::labs(
    title = "Sex hormone response scores across Figure 1b states",
    x = NULL,
    y = "Mean-expression module score, z-scaled"
  ) +
  ggplot2::theme_classic() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
    plot.title = ggplot2::element_text(hjust = 0.5),
    strip.background = ggplot2::element_blank()
  )

save_plot(p_violin, "03D_violin_sex_hormone_scores_by_stage", width = 7.5, height = 8.5)

# 按 sample/replicate 汇总，避免后续误把单细胞当生物学重复。
sample_score_summary <- stats::aggregate(
  score ~ stage_plot + exp + score_name,
  data = score_long,
  FUN = function(x) mean(x, na.rm = TRUE)
)

utils::write.csv(
  sample_score_summary,
  file = file.path(result_dir, "03D_sample_level_mean_scores_by_stage.csv"),
  row.names = FALSE,
  quote = FALSE
)

stage_score_summary <- stats::aggregate(
  score ~ stage_plot + score_name,
  data = score_long,
  FUN = function(x) mean(x, na.rm = TRUE)
)

utils::write.csv(
  stage_score_summary,
  file = file.path(result_dir, "03D_stage_level_mean_scores.csv"),
  row.names = FALSE,
  quote = FALSE
)

# -------------------------------------------------------------------------
# 8. 相关性热图：sex hormone variables vs mTEC/tolerance/mimetic variables
# -------------------------------------------------------------------------

cat("\n===== 6. Correlation heatmap =====\n")

bio_score_columns <- c(
  "Aire_Fezf2_core_z",
  "Antigen_presentation_z",
  "Tuft_program_z",
  "Ccl21a_high_program_z",
  "cTEC_program_z"
)
bio_score_columns <- intersect(bio_score_columns, colnames(figure1b_obj[[]]))

core_marker_genes <- c(
  "Aire", "Fezf2", "Ccl21a", "Krt5", "Krt14",
  "Pou2f3", "Trpm5", "Dclk1",
  "Cd74", "H2-Aa", "H2-Ab1", "B2m",
  "Ackr4", "Prss16", "Psmb11"
)
core_marker_genes <- intersect(core_marker_genes, rownames(figure1b_obj))

x_vars <- unique(c(present_receptors, sex_score_columns))
y_vars <- unique(c(core_marker_genes, bio_score_columns))

fetch_vars <- unique(c(x_vars, y_vars))
fetch_df <- Seurat::FetchData(
  object = figure1b_obj,
  vars = fetch_vars,
  slot = "data"
)

# 去掉全 NA 或方差为 0 的变量。
valid_var <- vapply(
  fetch_df,
  function(x) {
    x <- as.numeric(x)
    sum(is.finite(x)) > 3 && stats::sd(x, na.rm = TRUE) > 0
  },
  logical(1)
)
fetch_df <- fetch_df[, valid_var, drop = FALSE]

x_vars <- intersect(x_vars, colnames(fetch_df))
y_vars <- intersect(y_vars, colnames(fetch_df))

if (length(x_vars) > 0 && length(y_vars) > 0) {
  cor_mat <- stats::cor(
    fetch_df[, x_vars, drop = FALSE],
    fetch_df[, y_vars, drop = FALSE],
    method = "spearman",
    use = "pairwise.complete.obs"
  )

  utils::write.csv(
    cor_mat,
    file = file.path(result_dir, "03E_spearman_correlation_matrix.csv"),
    quote = FALSE
  )

  cor_long <- as.data.frame(as.table(cor_mat), stringsAsFactors = FALSE)
  colnames(cor_long) <- c("sex_hormone_variable", "mtec_variable", "spearman_r")

  cor_long$sex_hormone_variable <- factor(
    cor_long$sex_hormone_variable,
    levels = rev(x_vars)
  )
  cor_long$mtec_variable <- factor(
    cor_long$mtec_variable,
    levels = y_vars
  )

  p_cor <- ggplot2::ggplot(
    cor_long,
    ggplot2::aes(x = mtec_variable, y = sex_hormone_variable, fill = spearman_r)
  ) +
    ggplot2::geom_tile(color = "white", linewidth = 0.25) +
    ggplot2::scale_fill_gradient2(
      low = "#2166AC",
      mid = "white",
      high = "#B2182B",
      midpoint = 0,
      limits = c(-1, 1),
      name = "Spearman\nr"
    ) +
    ggplot2::labs(
      title = "Association between sex hormone variables and mTEC programs",
      x = NULL,
      y = NULL
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
      plot.title = ggplot2::element_text(hjust = 0.5)
    )

  save_plot(p_cor, "03E_correlation_heatmap", width = 10, height = 4.8)
} else {
  warning("Not enough valid variables to create the correlation heatmap.")
}

# -------------------------------------------------------------------------
# 9. 保存对象、summary 和 sessionInfo
# -------------------------------------------------------------------------

cat("\n===== 7. Saving final object and summary =====\n")

saveRDS(control_obj, file = result_file)

summary_file <- file.path(result_dir, "03_sex_hormone_figure1b_summary.txt")

summary_lines <- c(
  paste0("Input object: ", input_file),
  paste0("Output object: ", result_file),
  paste0("Output directory: ", result_dir),
  "",
  "Dataset positioning:",
  "  Figure 1b atlas is treated as a female WT mTEC developmental atlas.",
  "  This script does not perform male-vs-female comparisons.",
  "  This script analyzes androgen/estrogen/progesterone axes only.",
  "",
  paste0("Cells in full object: ", ncol(control_obj)),
  paste0("Cells in Figure 1b object after removing unknown: ", ncol(figure1b_obj)),
  paste0("UMAP reduction used: ", reduction_name),
  "",
  "Sex hormone receptor genes requested:",
  paste0("  ", paste(sex_receptors, collapse = ", ")),
  "Present receptor genes:",
  paste0("  ", paste(present_receptors, collapse = ", ")),
  "Missing receptor genes:",
  paste0("  ", paste(missing_receptors, collapse = ", ")),
  "",
  "Score columns added:",
  paste0("  ", paste(score_columns, collapse = ", ")),
  "",
  "Cells per Figure 1b state:",
  paste(capture.output(print(sort(table(figure1b_obj$stage_plot), decreasing = TRUE))), collapse = "\n"),
  "",
  "Main output files:",
  "  03A_dotplot_sex_receptors_by_stage.png/pdf",
  "  03B_featureplot_<gene>.png/pdf",
  "  03C_featureplot_<score>.png/pdf",
  "  03D_violin_sex_hormone_scores_by_stage.png/pdf",
  "  03E_correlation_heatmap.png/pdf",
  "  03C_gene_set_summary.csv",
  "  03D_sample_level_mean_scores_by_stage.csv",
  "  03E_spearman_correlation_matrix.csv"
)

writeLines(summary_lines, summary_file)

session_file <- file.path(result_dir, "03_sessionInfo.txt")
writeLines(capture.output(sessionInfo()), session_file)

cat("\nDone.\n")
cat("Saved object:\n", result_file, "\n", sep = "")
cat("Saved summary:\n", summary_file, "\n", sep = "")
cat("Saved session information:\n", session_file, "\n", sep = "")
cat("Saved plots and tables under:\n", result_dir, "\n", sep = "")
